version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - car_rental_network

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_rental_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/car_rental?schema=public"
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - car_rental_network
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:

networks:
  car_rental_network:
    driver: bridge